### PR TITLE
DPL-1056 - Removed breaking restriction

### LINKED ISSUE #701: DPL-1056 Unable to create buildings in LabWhere [Could've]
When creating a building in LabWhere create location tab the page is loading very slow, once it does load it doesn't create the building. It will return to the same page
lw_building_page_error

Relates to [RT795753](https://rt.sanger.ac.uk/Ticket/Display.html?id=795753)

Also relates to story DPL-758 https://github.com/sanger/labwhere/issues/649
where the same issue was found when creating rooms

Note: The building require in the RT (RSF) has been created via the console.

### PR DESCRIPTION
**Pull request by SHIV5T3R**
Closes #701 

#### Changes proposed in this pull request

- Removed a restriction that would prevent new locations from being added if the same location type was being used

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

### CODE REVIEW

**Review by dasunpubudumal — COMMENTED** [review]
@SHIV5T3R the change looks good. 

A small thing; the `README.md` doesn't have any instruction on setting up `bunny.yml` file. I imagine one has to go to the workflow (in `.github` directory) to find out how to utilise it. When I was first setting it up, I ran to an error saying the `bunny.yml` was not found.

Do you think that we could improve the `README.md` to include instructions on the `bunny.yml` file?

**Review by KatyTaylor — APPROVED** [review]
Looks good. 

On the related story, Harry wrote: 

> After removing this, the behaviour is still the same as previously .... Another room with the same name cannot be created, because of the validation validates :name, presence: true, uniqueness: { scope: :ancestry, case_sensitive: true } in the location class, but another location type with the same name can still be created.

(https://github.com/sanger/labwhere/issues/649#issuecomment-1578804917)

I assume that's still true here.

**Review by dasunpubudumal — APPROVED** [review]

**Comment by KatyTaylor** [comment]
> @SHIV5T3R the change looks good.
> 
> A small thing; the `README.md` doesn't have any instruction on setting up `bunny.yml` file. I imagine one has to go to the workflow (in `.github` directory) to find out how to utilise it. When I was first setting it up, I ran to an error saying the `bunny.yml` was not found.
> 
> Do you think that we could improve the `README.md` to include instructions on the `bunny.yml` file?

I've done this in a separate PR :)  https://github.com/sanger/labwhere/pull/745

**Comment by dasunpubudumal** [comment]
> @SHIV5T3R the change looks good.
> 
> A small thing; the `README.md` doesn't have any instruction on setting up `bunny.yml` file. I imagine one has to go to the workflow (in `.github` directory) to find out how to utilise it. When I was first setting it up, I ran to an error saying the `bunny.yml` was not found.
> 
> Do you think that we could improve the `README.md` to include instructions on the `bunny.yml` file?

Disregard this. Just saw Katy had updated the `README`. All good!

**Pull request merged**
